/**
 * Top-level route registration. Each domain mounts its own Router under a
 * stable URL prefix; the createApp() factory consumes this single function.
 */
import type { Application } from 'express';
import authRouter from './auth';
import portalAuthRouter from './portal-auth';
import rbacRouter from './rbac';
import modulesRouter from './modules';
import workflowsRouter from './workflows';
import auditRouter from './audit';
import usersRouter from './users';
import organizationRouter from './organization';
import branchesRouter from './branches';
import departmentsRouter from './departments';
import designationsRouter from './designations';
import locationsRouter from './locations';
import rolesRouter from './roles';
import permissionsRouter from './permissions';
import documentsRouter from './documents';
import fieldVisibilityRouter from './field-visibility';
import customFieldsRouter from './custom-fields';
import fieldConfigRouter from './field-config';
import emailProvidersRouter from './email-providers';
import emailTemplatesRouter from './email-templates';
import smsProvidersRouter from './sms-providers';
import smsTemplatesRouter from './sms-templates';
import whatsappProvidersRouter from './whatsapp-providers';
import whatsappTemplatesRouter from './whatsapp-templates';
import whatsappWebhookRouter from './whatsapp-webhook';
import notificationsRouter from './notifications';
import adminNotificationsRouter from './admin-notifications';
import oauthRouter from './oauth';
import dpdpRouter from './dpdp';
import paymentsRouter from './payments';
import paymentWebhookRouter from './payment-webhook';
import adminPaymentsRouter from './admin-payments';
import adminCustomersRouter from './admin-customers';
import publicSignupRouter from './public-signup';
import portalUsersRouter from './portal-users';
import adminNumberingRouter from './admin-numbering';
import adminSettingsRouter from './admin-settings';
import customersRouter from './customers';
import productsRouter from './products';
import productCategoriesRouter from './product-categories';
import ordersRouter from './orders';
import paymentTermsRouter from './payment-terms';
import materialsRouter from './materials';
import manufacturerCatalogsRouter from './manufacturer-catalogs';
import { materialImagesRouter, adminMaterialImagesRouter } from './material-images';
import materialImportRouter from './material-import';
import processesRouter from './processes';
import bomsRouter from './boms';
import selectionListsRouter from './selection-lists';
import resolvedBomsRouter from './resolved-boms';
import costingRouter from './costing';
import reportsRouter from './reports';
import portalSelectionListsRouter from './portal-selection-lists';
import vendorsRouter from './vendors';
import storageRouter from './storage';
import purchaseRequisitionsRouter from './purchase-requisitions';
import purchaseOrdersRouter from './purchase-orders';
import importShipmentsRouter from './import-shipments';
import grnsRouter from './grn';
import qualityInspectionsRouter from './quality-inspections';
import inventoryRouter from './inventory';
import materialRequisitionsRouter, { minRouter, mrnRouter } from './material-requisitions';
import stockCountsRouter, { adjustmentsRouter } from './stock-counts';
import phase3IntegrationRouter from './phase3-integration';
import { vendorImportRouter, stockImportRouter } from './vendor-import';

export function registerRoutes(app: Application): void {
  app.use('/api/auth', authRouter);
  app.use('/api/portal/auth', portalAuthRouter);
  app.use('/api/rbac', rbacRouter);
  app.use('/api/modules', modulesRouter);
  app.use('/api/workflows', workflowsRouter);
  app.use('/api/audit', auditRouter);
  app.use('/api/users', usersRouter);
  app.use('/api/organization', organizationRouter);
  app.use('/api/branches', branchesRouter);
  app.use('/api/departments', departmentsRouter);
  app.use('/api/designations', designationsRouter);
  app.use('/api/locations', locationsRouter);
  app.use('/api/roles', rolesRouter);
  app.use('/api/permissions', permissionsRouter);
  app.use('/api/documents', documentsRouter);
  app.use('/api/admin/field-visibility', fieldVisibilityRouter);
  app.use('/api/admin/custom-fields', customFieldsRouter);
  app.use('/api/entities', fieldConfigRouter);
  app.use('/api/admin/email-providers', emailProvidersRouter);
  app.use('/api/admin/email-templates', emailTemplatesRouter);
  app.use('/api/admin/sms-providers', smsProvidersRouter);
  app.use('/api/admin/sms-templates', smsTemplatesRouter);
  app.use('/api/admin/whatsapp-providers', whatsappProvidersRouter);
  app.use('/api/admin/whatsapp-templates', whatsappTemplatesRouter);
  app.use('/api/webhooks/whatsapp', whatsappWebhookRouter);
  app.use('/api/notifications', notificationsRouter);
  app.use('/api/admin/notifications', adminNotificationsRouter);
  app.use('/api/auth/oauth', oauthRouter);
  app.use('/api/dpdp', dpdpRouter);
  app.use('/api/payments', paymentsRouter);
  app.use('/api/webhooks', paymentWebhookRouter);
  app.use('/api/admin', adminPaymentsRouter);
  app.use('/api/admin', adminCustomersRouter);
  app.use('/api/public', publicSignupRouter);
  app.use('/api/portal', portalUsersRouter);
  app.use('/api/admin', adminNumberingRouter);
  app.use('/api/admin', adminSettingsRouter);
  app.use('/api/customers', customersRouter);
  app.use('/api/products', productsRouter);
  app.use('/api/product-categories', productCategoriesRouter);
  app.use('/api/orders', ordersRouter);
  app.use('/api/admin/payment-terms-templates', paymentTermsRouter);
  app.use('/api/material', materialImportRouter);
  app.use('/api/material', materialsRouter);
  app.use('/api/material', manufacturerCatalogsRouter);
  app.use('/api/material', materialImagesRouter);
  app.use('/api/admin/material', adminMaterialImagesRouter);
  app.use('/api/processes', processesRouter);
  app.use('/api/boms', bomsRouter);
  app.use('/api/selection-lists', selectionListsRouter);
  app.use('/api/resolved-boms', resolvedBomsRouter);
  app.use('/api/costing', costingRouter);
  app.use('/api/reports', reportsRouter);
  app.use('/api/portal/selection-lists', portalSelectionListsRouter);

  // Phase 3 — Supply Chain & Procurement
  app.use('/api/vendors', vendorsRouter);
  app.use('/api/storage', storageRouter);
  app.use('/api/purchase-requisitions', purchaseRequisitionsRouter);
  app.use('/api/purchase-orders', purchaseOrdersRouter);
  app.use('/api/import-shipments', importShipmentsRouter);
  app.use('/api/grns', grnsRouter);
  app.use('/api/quality-inspections', qualityInspectionsRouter);
  app.use('/api/inventory', inventoryRouter);
  app.use('/api/material-requisitions', materialRequisitionsRouter);
  app.use('/api/material-issue-notes', minRouter);
  app.use('/api/material-return-notes', mrnRouter);
  app.use('/api/stock-counts', stockCountsRouter);
  app.use('/api/stock-adjustments', adjustmentsRouter);

  // Phase 3 — Integration & Imports
  app.use('/api/supply-integration', phase3IntegrationRouter);
  app.use('/api/vendors', vendorImportRouter);
  app.use('/api/inventory', stockImportRouter);
}
